--- "Saif Ali" Red Hat Inc
- hosts: all
   vars_files: 
     - var.yml
   handlers:
   - name: restart httpd
     service:
      name: httpd
      state: restarted
   - name: restart sssd
     service:
      name: sssd
      state: restarted
   tasks:
   - name: Adding the domain to the hosts file 
     lineinfile:
      dest: /etc/hosts
      line: "{{ domainip }} {{ domain }}"
      backup: yes
     ignore_errors: yes
   - name: joining CFME to the domain
     shell: 'echo "{{ passwd }}"| realm join "{{ domain }}" -U "{{ domainuser }}"'
   - name: updating sssd to get ldap users attributes from AD domain
     lineinfile:
      dest: /etc/sssd/sssd.conf
      line: 'ldap_user_extra_attrs = mail, givenname, sn, displayname'
      insertbefore: "^cache_credentials"
      backup: yes
   - name: updating sssd to get ldap users attributes from AD domain
     lineinfile:
      dest: /etc/sssd/sssd.conf
      line: 'ldap_user_extra_attrs = mail, givenname, sn, displayname'
      insertbefore: "^cache_credentials"
      backup: yes
   - replace:
       dest: /etc/sssd/sssd.conf
       backup: yes
       regexp: '^services(\s+.*)?$'
       replace: 'services = nss, sudo, pam, ssh, ifp'
   - name: updating sssd to get ldap users attributes from AD domain
     blockinfile:
      dest: /etc/sssd/sssd.conf
      block: |
             [ifp]
             allowed_uids = apache, root
             user_attributes = +mail, +givenname, +sn, +displayname
      insertafter: "[ifp]"
     notify: restart sssd
   - name: adding kerberos keytab file
     file:
      dest: /etc/krb5.keytab
      state: file
      group: apache
      mode: 0640
   - name: copying pam module
     copy:
      dest: /etc/pam.d/
      src: /opt/rh/cfme-appliance/TEMPLATE/etc/pam.d/httpd-auth
      remote_src: True
   - name: copying remote user config file
     copy:
      src: /opt/rh/cfme-appliance/TEMPLATE/etc/httpd/conf.d/manageiq-remote-user.conf
      dest: /etc/httpd/conf.d/
      remote_src: True
   - copy:
      src: /opt/rh/cfme-appliance/TEMPLATE/etc/httpd/conf.d/manageiq-external-auth.conf.erb
      dest: /etc/httpd/conf.d/manageiq-external-auth.conf
      remote_src: True
   - name: updating selinux
     seboolean:
      name: httpd_mod_auth_pam
      state: yes
      persistent: yes
   - seboolean:
      name: httpd_dbus_sssd
      state: yes
      persistent: yes
   - name: updating apache config
     replace: 
      dest: /etc/httpd/conf.d/manageiq-external-auth.conf
      regexp: ' KrbAuthRealms(\s+.*)?$'
      replace: ' KrbAuthRealms    {{ domain|upper }}'
     notify: restart httpd
